name: test
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
env:
  GO_VERSION: 1.x
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        go run . -format=github-actions findtypos . || true
